services:
  app:
    restart: always
    build: .
    ports:
      - 4000:4000
    working_dir: /app
    environment:
      - PORT=${PORT}
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - ADMIN_SECRET=${ADMIN_SECRET}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - realtime-db:/db

volumes:
  realtime-db:
