name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: |
          touch .env
          echo PORT=${{secrets.PORT}} >> .env
          echo DATABASE_URL=${{secrets.DATABASE_URL}} >> .env
          echo JWT_SECRET=${{secrets.JWT_SECRET}} >> .env
          echo ADMIN_SECRET=${{secrets.ADMIN_SECRET}} >> .env
          echo OPENAI_API_KEY=${{secrets.OPENAI_API_KEY}} >> .env
          sudo docker compose config
          sudo docker compose -p api up --build -d
