name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: sudo docker compose -p api up --build -d -e DATABASE_URL=${{ secrets.DATABASE_URL }} -e JWT_SECRET=${{ secrets.DATABASE_URL }} -e ADMIN_SECRET=${{ secrets.ADMIN_SECRET }} -e PORT=${{ secrets.PORT }} 
